### ISSUE TITLE
Open Source Here Maps JS SDK

### ISSUE THREAD

**Issue by kjellski** [heremaps/maps-api-for-javascript-examples#51]
Hi dear HERE Maps JS SDK Team,

I wanted to up front really thank you for all your hard work on this SDK! I originally wanted to ask for `source-maps` for this fine SDK in order to be able to debug problems on my usage of the SDK, but that is probably pretty much the same as asking for that to be open sourced completely. 

I couldn't find any issues with regards to the topic so I figured we might just kick of the discussion here.

My biggest concern is that I'm unable to help myself when writing buggy code against your API because it's already minified and uglified. Here is an example Stack Track:

```
"Error
    at new C (https://js.api.here.com/v3/3.1/mapsjs-core.js:35:1007)
    at B (https://js.api.here.com/v3/3.1/mapsjs-core.js:27:55)
    at ki.add (https://js.api.here.com/v3/3.1/mapsjs-core.js:172:707)
    at Q.Ng (https://js.api.here.com/v3/3.1/mapsjs-core.js:352:249)
    at HereMapsUtils.drawServiceAreaPolygon (http://localhost:8080/main.bundle.js:263558:47)
    at HereMapsUtils.drawServiceAreaOnMap (http://localhost:8080/main.bundle.js:263430:12)
    at StopNetworkMap.renderMap (http://localhost:8080/main.bundle.js:260531:25)
    at StopNetworkMap.renderMap (http://localhost:8080/main.bundle.js:163512:25)
    at StopNetworkMap.componentDidUpdate (http://localhost:8080/main.bundle.js:260517:10)
    at StopNetworkMap.componentDidUpdate (http://localhost:8080/main.bundle.js:163502:123)"
```

I would love this to be a dialog with you explaining your reasoning and maybe providing some insights on the topic.

Thank you for the already great work and the SDK we are able to use 🙏 

Best regards,
@kjellski

**Comment by kplotnik** [comment]
Unfortunately we do not plan open source the project at this point in time, as open sourcing the work is a little bit more work than just dumping code to the github ;) But we striving to improve the API so that it is easier to work with it. If you came across an instance where the error message is not meaningful or there is an inconsistency within the API please open the issue here and we will try fix it in the shortest time possible.

**Comment by kjellski** [comment]
Well and that's it? I mean you can still make it open source and let the community help with what's needed to make it a pleasant experience. 
We're here to do exactly that: help you do the work.

>  If you came across an instance where the error message is not meaningful or there is an inconsistency within the API please open the issue here and we will try fix it in the shortest time possible.

I posted one, right above! Now tell me what's wrong with it... I fixed what I needed to in that case, but you have to poke arround for exactly no apparent reason. Which _is_ the reason why I opened the ticket in the first place.

Why did you close the ticket? I would love to have a dialog :)
